### ISSUE TITLE
Your plugin does not understand that the round has been restarted

### ISSUE THREAD

**Issue by Tamago4a** [KadeDev/Common-Utils#14]
Your plugin does not understand that the round has been restarted. 
It does not reset the "autonuke_time: 900" counter. Perhaps it depends on the fact that I press a forced restart. But this is not an admin error, it is a mistake in terms of coding.
```yaml
CommonUtilities:
# Wether or not debug messages should be shown.
  debug: true
  # Wether or not SCP-049 should be able to talk to humans.
  scp049_speech: true
  # The text displayed at the timed interval specified below.
  timed_broadcast: <color=white>На сервер завезли много плагинов. Мне нужно чтобы вы сообщали о всех багах(желательно с скриншотами) в наш дискорд - <color=red>discord.gg/BYQ4DS7</color></color>
  # The time each timed broadcast will be displayed.
  timed_broadcast_duration: 5
  # The delay between each timed broadcast. To disable timed broadcasts, set this to 0
  timed_broadcast_delay: 0
  # The message displayed to the player when they first join the server. Setting this to empty will disable these broadcasts.
  join_message: <color=white><size=32>Привет <color=lime>%player%</color>! Помни если не будешь ливать то 20 игроков быстро наберутся! \nЗаходи в наш Discord! Скоро там будет ещё один конкурс на получение админки LVL2.</size></color>
  # The amount of time (in seconds) the join message is displayed.
  join_message_duration: 15
  # The amount of time (in seconds) after the round starts, before the facilities auto-nuke will start.
  autonuke_time: 900
  # Wether or not the nuke should be unable to be disabled during the auto-nuke countdown.
  autonuke_lock: true
  # The list of items Class-D should have. Valid formatting should be ItemType:Chance where ItemType is the item to give them, and Chance is the percent chance of them spawning with it. You can specify the same item multiple times. This is true for all Inventory configs.
  class_d_inventory:
  - KeycardJanitor:50
  - Adrenaline:1
  - Flashlight:5
  chaos_inventory:
  - KeycardChaosInsurgency:100
  - GunLogicer:100
  - GrenadeFlash:20
  - Radio:100
  - Disarmer:100
  - Flashlight:100
  - Medkit:100
  - Adrenaline:3
  scientist_inventory:
  - KeycardScientist:100
  - Flashlight:100
  - Medkit:100
  - Painkillers:100
  - Adrenaline:20
  - GunCOM15:5
  - Ammo9mm:5
  guard_inventory:
  - KeycardGuard:100
  - GunUSP:100
  - GrenadeFlash:20
  - Radio:100
  - WeaponManagerTablet:40
  - Painkillers:100
  - Adrenaline:3
  cadet_inventory:
  - KeycardSeniorGuard:100
  - GunMP7:100
  - GrenadeFlash:20
  - Radio:100
  - Flashlight:100
  - Painkillers:100
  - Adrenaline:3
  lieutenant_inventory:
  - KeycardNTFLieutenant:100
  - GunProject90:100
  - GrenadeFlash:20
  - Radio:100
  - Disarmer:100
  - Flashlight:100
  - WeaponManagerTablet:40
  - Painkillers:100
  commander_inventory:
  - KeycardNTFCommander:100
  - GunE11SR:100
  - GrenadeFrag:100
  - Radio:100
  - Disarmer:100
  - Flashlight:100
  - Medkit:100
  - MicroHID:3
  - WeaponManagerTablet:40
  - Adrenaline:3
  ntf_sci_inventory:
  - KeycardNTFLieutenant:100
  - GunProject90:100
  - GrenadeFlash:20
  - Radio:100
  - Flashlight:100
  - WeaponManagerTablet:40
  - Medkit:100
  - Adrenaline:100
  # The list of custom 914 recipies for the Rough setting. Valid formatting should be OriginalItemType:NewItemType:Chance where OriginalItem is the item being upgraded, NewItem is the item to upgrade to, and Chance is the percent chance of the upgrade happening. You can specify multiple upgrade choices for the same item. This is true for all 914 configs.
  scp914_rough_chances: []
  scp914_coarse_chances: []
  scp914_oneto_one_chances: []
  scp914_fine_chances: []
  scp914_very_fine_chances: []
  # The frequency (in seconds) between ragdoll cleanups. Set to 0 to disable.
  ragdoll_cleanup_delay: 0
  # If ragdoll cleanup should only happen in the Pocket Dimension or not.
  ragdoll_cleanup_only_pocket: false
  # The frequency (in seconds) between item cleanups. Set to 0 to disable.
  item_cleanup_delay: 0
  # If item cleanup should only happen in the Pocket Dimension or not.
  item_cleanup_only_pocket: false
  # A list of roles and how much health they should be given when they kill someone.
  health_on_kill:
    Scp173: 125
    Scp096: 70
  # A list of roles and what their default starting health should be.
  health_values:
    Scp173: 3200
    NtfCommander: 160
  # If the plugin is enabled or not.
  is_enabled: true
```

https://www.youtube.com/watch?v=-TouBJygG0I
