### ISSUE TITLE
Preallocate all classes for health_on_kill and health_values

### ISSUE THREAD

**Issue by PatPeter** [KadeDev/Common-Utils#21]
Instead of arbitrarily setting SCP-173 to 3,000 health and NTF Commanders to 200 health, why not default all `health_values` to the default health of every class in the game? Yes, this would have to be changed after any balance updates, but most of these health values have been consistent for over 2 years so that isn't a large cause for concern.

In addition, by having every class in `health_on_kill` and `health_values` by default, there's no need to reference the #resources channel in the EXILED Discord to figure out what the exact key is (for those new to EXILED).

This also doesn't change any default gameplay when Common Utilities is initially installed on the server.

```
  # A list of roles and how much health they should be given when they kill someone.
  health_on_kill:
    Scp173: 0
    Scp106: 0
    Scp049: 0
    Scp0492: 0
    Scp096: 0
    Scp93953: 0
    Scp93989: 0
    ChaosInsurgency: 0
    ClassD: 0
    Scientist: 0
    FacilityGuard: 0
    NtfCadet: 0
    NtfScientist: 0
    NtfLieutenant: 0
    NtfCommander: 0
    Tutorial: 0
  # A list of roles and what their default starting health should be.
  health_values:
    Scp173: 3200
    Scp106: 650
    Scp049: 1700
    Scp0492: 300
    Scp096: 1500
    Scp93953: 2200
    Scp93989: 2200
    ChaosInsurgency: 120
    ClassD: 100
    Scientist: 100
    FacilityGuard: 100
    NtfCadet: 100
    NtfScientist: 120
    NtfLieutenant: 120
    NtfCommander: 150
    Tutorial: 100
```
